### ISSUE TITLE
Should we move remote to https://github.com/zynthian/ZynthianOS ?

### ISSUE THREAD

**Issue by guysoft** [guysoft/ZynthianOS#12]
@jofemodo 
At the moemnet the nightly is running against https://github.com/guysoft/ZynthianOS
I can see two extra commits there.

Do you want to stay here or move there?

**Comment by jofemodo** [comment]
Ohh! In fact, it's not very important for me. I understand the point of having all "CustomPiOS" derivatives under "guysoft" trunk. and it's perfectly OK for me (and zynthian) ;-) Having write access to the repo should be enough.

I will merge my changes and delete the fork under Zynthian for avoid confusion. It's not needed anymore.

BTW, thanks a lot for your help. Releasing the new image is a huge effort because zynthian's software has become quite complex in the last 2 years. I can't imagine how i would managed the task without ZynthianOS & Jenkins ... you saved my life, man!! Truly!!

**Comment by guysoft** [comment]
CustomPiOS is actually a toolkit.  It makes much more sense for it to be in
the zynthian project side. You should be its owner :)

**Comment by jofemodo** [comment]
Then, i will move to Zynthian. As i told you, it's not very important for me. I thought you liked to have the "children" in the same room, but if you think it would be better under the zynthian umbrella, nice. I will follow your advice, of course ;-)

**Comment by jofemodo** [comment]
OK! It's changed now. Thanks!
